### ISSUE TITLE
install miktex into ubuntu

### ISSUE THREAD

**Issue by ChefOtter** [MiKTeX/miktex-testing#1]
Hi,
I try to install miktex under ubuntu, but it doesn't work.
I installed all dependencies which you described in Readme.unx file. I followed instructions,
but at the end i got just errors.
Errors is about the 
> no matching function for call to OMEGACLASS::Free(asciicode) [80001])

i can start make command and it does work but after %78 it breaks down. There are errors.

Is there any suggestion how can i install miktex into ubuntu? Or miktex is just for windows?
regards

**Comment by edocevoli** [comment]
Sorry, but the issue tracker has not been opened (yet).
